version: "3.7"

services:
  px4_docker:
    image: jonasvautherin/px4-gazebo-headless:1.13.0
    ports:
      - "50051:50051"
      - "14540:14540"
      - "14550:14550"
    command: apt-get install netcat && cd /root && ./entrypoint.sh
    healthcheck:
          test: ["CMD", "curl", "-f", "0.0.0.0:4560"]
          interval: 30s
          retries: 100
          start_period: 30s
          timeout: 30s

  test:
    build: .
    depends_on:
      - px4_docker
    links:
      - "px4_docker:px4"
    command: sh -c "/wait && echo Done"
    environment:
      - WAIT_HOSTS=px4_docker:50051,px4_docker:14540
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30