version: "3.7"

services:
  px4_docker:
    image: jonasvautherin/px4-gazebo-headless
    ports:
      - "50051:50051"
      - "14540:14540"
      - "14550:14550"
    healthcheck:
          test: ss -tulpn | grep LISTEN | grep gzserver
          interval: 60s
          timeout: 10s
          retries: 10
          start_period: 30s

  test:
    build: .
    depends_on:
      - px4_docker
    links:
      - "px4_docker:px4"
    command: sh -c "./wait && echo Done"
    environment:
      - WAIT_HOSTS=px4_docker:50051,px4_docker:14540
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30