name: Black Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  black_check:
    name: "Check Black Formatting"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Black Formatting
      run: |
        pip install black
        
        black --check ./pteranodon