name: PyPI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_check:
    name: "Build pteranodon package"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        ./scripts/install.sh

    - name: Clone Submodules
        if: ${{ github.event.pull_request.head.ref != '' }}
        run: |
          git submodule init
          git pull origin $BRANCH_REF --recurse-submodules
          git submodule update --init --resursive
    - name: Clone Submodules
        if: ${{ github.event.pull_request.head.ref == '' }}
        run: |
          git submodule init
          git pull origin main --recurse-submodules
          git submodule update --init --resursive

    - name: Install build
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build pteranodon
      run: |
        python -m build

