name: Formatting Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  black_check:
    name: "Check Black Formatting"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        ./scripts/install.sh
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -r requirements-extras.txt

    - name: Check Black Formatting
      run: |
        black --check ./src

  flake8_check:
    name: "Flake8 Format Checking"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        ./scripts/install.sh
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -r requirements-extras.txt

    - name: Lint with flake8
      run: |
        # stop the build if there are...
        # Python syntax errors or undefined names
        # Unused imports
        # No new line
        # No whitespace after keyword


        # Ignore...
        # Whitespace in new line
        # Trailing whitespace
        # Too many blank lines
        # Whitespace before :, Line break occurred before a binary operator (Black breaks this)

        flake8 ./src --count --select=E9,F63,F7,F82,F401,W292,E275,F403 --extend-ignore=W293,W291,E303,E203,W503 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./src --count --exit-zero --max-complexity=10 --max-line-length=140 --statistics

  mypy_check:
    name: "MyPy linting check"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        ./scripts/install.sh
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -r requirements-extras.txt

    - name: Lint with mypy
      run: |
        mypy ./src --no-implicit-optional --show-column-numbers --show-error-codes --disable-error-code import

  pylint_check:
    name: "PyLint check"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        ./scripts/install.sh
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -r requirements-extras.txt

    - name: Lint with pylint
      run: |
        # Ignore...
        # Wildcard import,
        # Trailing whitespace
        # Missing module docstring
        # Too many instance attributes
        # Too many public methods
        # Multiple trailing newlines
        # Too broad of an exception
        # consider-using-enumerate
        # Too many arguments
        # Too many local variables
        # Unnecessary pass statement
        # Logging fstring interpolation
        # Useless parent or super() delegation 

        pylint ./src --disable=C0303,C0114,W0401,R0902,R0904,C0305,W0703,C0200,R0913,R0914,W0107,W1203,W0246

