name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  offboard:
    name: "Test Offboard"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/test-requirements.txt
      - name: Startup PX4 Docker
        run: |
          docker run --rm -dt jonasvautherin/px4-gazebo-headless:1.13.0
          sleep 10
      - name: Test Abstract Plugin
        run: |
          pytest tests/integration/test_offboard.py