name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  offboard:
    name: "Test Offboard"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/test-requirements.txt
      - name: Test Abstract Plugin
        run: |
          pytest --log-cli-level=INFO --full-trace -rP tests/integration/test_offboard.py --hostname=px4_docker

    services:
      px4_docker:
        image: jonasvautherin/px4-gazebo-headless:1.13.0
        ports:
          - "50051:50051"
          - "14540:14540/udp"