name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  offboard:
    name: "Test Offboard"

    runs-on: ubuntu-latest
    env:
      BRANCH_REF: "${{ github.event.pull_request.head.ref }}"

    steps:
      - uses: actions/checkout@v1

      - name: Build Docker Containers
        run: | #Build Docker Container
          docker compose -f .ci/tests-docker-compose.yaml -p tests-services build --build-arg GIT_REF_NAME="$BRANCH_REF"

      - name: Check Running Containers 0 
        run: | #List running containers
          docker ps -a

      - name: Run Docker Containers
        run: | #Run container
          docker compose -f .ci/tests-docker-compose.yaml -p tests-services up --no-recreate --wait | echo "commander takeoff"
          sleep 10
          docker ps -a
        #docker compose -f .ci/tests-docker-compose.yaml -p tests-services up -d --no-recreate --wait

      - name: Check Running Containers 1 
        run: | #List running containers
          docker ps -a

      - name: Test Abstract Plugin
        run: | #Run test code
          docker compose -f .ci/tests-docker-compose.yaml -p tests-services exec tests-services-px4_docker-1 python3 test_script.py px4
        #docker compose -f .ci/tests-docker-compose.yaml -p tests-services exec -T test python3 test_script.py px4

      - name: Check Running Containers 2 
        run: | #List running containers
          docker ps -a
