name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  offboard:
    name: "Test Offboard"

    runs-on: ubuntu-latest
    env:
      BRANCH_REF: "${{ github.event.pull_request.head.ref }}"

    steps:
      - uses: actions/checkout@v1
      - name: Start docker containers
        run: |
          echo "REFREF: $BRANCH_REF"
          docker-compose -f .ci/tests-docker-compose.yaml -p tests-services build \
          --build-arg GIT_REF_NAME="$BRANCH_REF" --build-arg TEST_FILE="tests/integration/test_offboard.py"
          docker-compose -f .ci/tests-docker-compose.yaml -p tests-services up -d --no-recreate
      - name: Test Abstract Plugin
        run: |
          docker-compose -f .ci/tests-docker-compose.yaml -p tests-services exec -T test python3 test_script.py
# pytest --log-cli-level=INFO --full-trace -rP integration/test_offboard.py --hostname=tests-services_px4_docker_1
#          pytest --log-cli-level=INFO --full-trace -rP tests/integration/test_offboard.py --hostname=px4_docker
#    services:
#      px4_docker:
#        image: jonasvautherin/px4-gazebo-headless:1.13.0
#
#        ports:
#          - "50051:50051"
#          - "14540:14540/udp"
#
#        options: >-
#          --health-cmd "ss --all | grep 14280"
#          --health-interval 5s
#          --health-timeout 100s
#          --health-retries 5
#          --health-start-period 500s