name: PEP-8 Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  mypy_check:
    name: "MyPy linting check"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with mypy
      run: |
        pip install mypy 
        mypy ./pteranodon --no-implicit-optional --show-column-numbers --show-error-codes --disable-error-code import