name: PEP-8 Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pylint_check:
    name: "PyLint check"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with pylint
      run: |
        pip install pylint pytest
        # Ignore...
        # Wildcard import,
        # Trailing whitespace
        # Missing module docstring
        # Too many instance attributes
        # Too many public methods
        # Multiple trailing newlines
        # Too broad of an exception
        # consider-using-enumerate
        # Too many arguments
        # Too many local variables
        # Unnecessary pass statement
        # Logging fstring interpolation
        # Useless parent or super() delegation 

        pylint ./pteranodon --disable=C0303,C0114,W0401,R0902,R0904,C0305,W0703,C0200,R0913,R0914,W0107,W1203,W0246